### ISSUE TITLE
Typos in spectra.ipynb

### ISSUE THREAD

**Issue by KshitijAggarwal** [HeloiseS/hoki_tutorials#1]
I ran spectra.ipynb for the JOSS [review](https://github.com/openjournals/joss-reviews/issues/1987), and noticed the following:
* While loading data for NGC4993, current `sep=r"\s*"` isn't able to read the data correctly, `"\s+"` seems to work. 
* `dopcor` appears to be making the correction in place, so 
`ngc4993_dopcor = dopcor(ngc4993_scaled, z=0.009727)`
`ngc4993_scaled['WL'] = ngc4993_dopcor['WL']`
can be replaced with just the function call. 
* and so `ngc4993_scaled` can be used instead of `ngc4993_dopcor` further in the notebook

**Comment by HeloiseS** [comment]
Thanks so much for going through the documentation so thoroughly!

- I changed the seperator argument :heavy_check_mark: 
- `dopcor` has changed and this wasn't reflected in the tutorial - now it does :heavy_check_mark:
