### ISSUE TITLE
Hoki CMD Age Wizard Tutorial

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki_tutorials#5]
Dear HOKI development team,
I, Ryota Inagaki, would like to know how to find the probability distribution functions for ages of the star not given explicitly a CMD file. 
How do I create the CMD model that can be passed into the Agewizard function using HOKI?

**Comment by HeloiseS** [comment]
Sorry for the delay Ryo thanks for your questions! 

You can create a CMD object using the recipe in those tutorials and it should work, just know that for now it's not a full release - if you have any issues let me know :D
