### ISSUE TITLE
Tutorial Pickle Column Issues

### ISSUE THREAD

**Issue by aadlander** [HeloiseS/hoki_tutorials#6]
In the tutorial https://github.com/HeloiseS/hoki_tutorials/blob/model_search_tuto/Model%20Search.ipynb the pickles that are downloadable (https://zenodo.org/record/3905388#.XvKgdHUzbmE) for the stellar models appear to be missing the data for the surface mass fractions for C and N.  Instead, when calling upon these columns in the DataFrame they give the surface mass fractions for O and Ne, respectively.  As such, calling upon the O and Ne columns also give values for different parameters.

What I did to check this:
```python
print(all_models_z006['filenames'][0])
print(all_models_z006['C'][0])
print(all_models_z006['N'][0])
print(all_models_z006['O'][0])
print(all_models_z006['Ne'][0])
```
Output:
```
NEWSINMODS/z006/sneplot-z006-65
0.002892
0.000594
47.77505
16.83502
```
Expected Output from NEWSINMODS/z006/sneplot-z006-65 file:
```
0.1038000E-02   
0.3162000E-03
0.2892000E-02   
0.5940000E-03
```

**Comment by HeloiseS** [comment]
All fixed - thanks for reporting! 

Updated data set is here https://zenodo.org/record/4064300#.X3fm63VfhNw

and the link is up to date in the tutorial :)
